services:
  - type: web
    name: cv-security-pipeline
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false